spring.application.name=carproject

# H2
spring.datasource.url=jdbc:mariadb://calfadventure.com:3306/car_project
spring.datasource.username=calfad_user
spring.datasource.password=Calfad@1006
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA ??
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DevTools ??
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

# ?? ??? ?? ?? (? ??)
# ?? ??? ?? ???? (CSS, JS ??? ??)
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.mail.username=djaxodbs010@gmail.com
spring.mail.password=ravoqcgracfwzeuv
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# OAuth2 ??? ??
spring.security.oauth2.client.registration.kakao.client-id=2da4e925cb390a0ee676856156508384
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB
