spring.application.name=carproject

# H2
spring.datasource.url=jdbc:mariadb://calfadventure.com:3306/car_project
spring.datasource.username=calfad_user
spring.datasource.password=Calfad@1006
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA ??
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DevTools ??
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

# ?? ??? ?? ?? (? ??)
# ?? ??? ?? ???? (CSS, JS ??? ??)
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.mail.username=djaxodbs010@gmail.com
spring.mail.password=ravoqcgracfwzeuv
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

